apiVersion: v1
kind: ConfigMap
metadata:
  name: mfe-sqctrl-legado-configmap
  namespace: miami
data:
  BFF_URL: https://bff.miami.sqfaas.in/sqctrl-legado/api
  URL_LEGADO: https://miami.sqfaas.dev/frontend
