apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: database
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/k8s-volumes/mongodb
