apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: staging1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: us-east1-docker.pkg.dev/prj-sqfaas-dev/sqfaas-dev/keycloak-v22:postgres
          command: ["/opt/keycloak/bin/kc.sh"]
          args: ["start", "--optimized", "--spi-theme-default=sinqia", "--hostname="]
          env:
            - name: TZ
              value: America/Sao_Paulo
            - name: KC_HOSTNAME
              value: "kc.staging1.sqfaas.in"
            - name: KC_HOSTNAME_URL
              value: "https://kc.staging1.sqfaas.in"
            - name: KC_HOSTNAME_ADMIN_URL
              value: "https://kc.staging1.sqfaas.in"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_TRANSACTION_XA_ENABLED
              value: "false"
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              value: postgres.storage.svc.cluster.local
            - name: KC_DB_URL_DATABASE
              value: keycloak_staging1
            - name: KC_DB_USERNAME
              value: sysdemo
            - name: KC_DB_PASSWORD
              value: demosys
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HTTPS_KEY_STORE_FILE
              value: "/opt/certs/sqfaas.jks"
            - name: KC_HTTPS_KEY_STORE_PASSWORD
              value: "demosys"
            - name: KC_HTTPS_KEY_ALIAS
              value: "sqfaas"
          ports:
            - containerPort: 8080
            - containerPort: 8443
          volumeMounts:
          - mountPath: /opt/certs
            name: secrets-files
            readOnly: true
      volumes:
      - name: secrets-files
        secret:
          secretName: secrets-files
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
