apiVersion: v1
kind: Service
metadata:
  labels:
    app: mfe-interoperabilidade
  name: mfe-interoperabilidade
  namespace: rio
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: mfe-interoperabilidade
