apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: database
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: sysdemo
            - name: POSTGRES_PASSWORD
              value: demosys
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgres
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
