apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: svc-downloader
  name: svc-downloader
  namespace: rio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-downloader
  template:
    metadata:
      labels:
        app: svc-downloader
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Djavax.net.ssl.trustStore=/usr/local/https/sqfaas.jks -Djavax.net.ssl.trustStorePassword=demosys
        envFrom:
        - configMapRef:
            name: bff-common-configmap
        - configMapRef:
            name: svc-downloader-configmap
        image: sinqia.azurecr.io/fundos/sqfaas/back/svc-downloader:1.0.0-MT-9
        imagePullPolicy: Always
        name: svc-downloader
        ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: /usr/local/https
          name: truststore
      imagePullSecrets:
      - name: acr-secret
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      volumes:
      - name: truststore
        secret:
          secretName: sqfaas-files
