apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-miami-pv-config
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/miami/config

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-miami-pv-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/miami/data

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-miami-pv-exports
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/miami/exports

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-miami-pv-filesportal
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/miami/filesportal

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-miami-pv-imports
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/miami/imports

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-miami-pv-shared
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/miami/shared

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-miami-pv-upload
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/miami/upload

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-certs-pv
  namespace: miami
spec:
  capacity:
    storage: 1Gi  
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: premium-rwo
  hostPath:
    path: /opt/certs/ 
    #type: Directory 

