apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bff-boletagem
  name: bff-boletagem
  namespace: staging1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff-boletagem
  template:
    metadata:
      labels:
        app: bff-boletagem
    spec:
      containers:
      - env:
        - name: SERVER_SERVLET_CONTEXTPATH
          value: /boletagem
        - name: SERVER_PORT
          value: '8081'
        - name: JAVA_OPTS
          value: -Djavax.net.ssl.trustStore=/opt/certs/sqfaas.jks -Djavax.net.ssl.trustStorePassword=demosy
        envFrom:
        - configMapRef:
            name: bff-common-configmap
        - configMapRef:
            name: bff-boletagem-configmap
        image: sinqia.azurecr.io/fundos/sqfaas/bff/psv-boletagem:1.1.0-rc.2
        imagePullPolicy: Always
        name: bff-boletagem
        ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: /opt/certs
          name: certs  # Aqui está o volume 'certs' que está sendo montado corretamente
          readOnly: true
      imagePullSecrets:
      - name: acr-secret
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      volumes:
        - name: certs
          secret:
            secretName: sqfaas-files
