apiVersion: v1
kind: Service
metadata:
  labels:
    app: bff-importacoes
  name: bff-importacoes
  namespace: ibiza
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: bff-importacoes
