apiVersion: v1
kind: Service
metadata:
  labels:
    app: mfe-indices-cotacoes
  name: mfe-indices-cotacoes
  namespace: staging1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: mfe-indices-cotacoes
