apiVersion: v1
kind: Service
metadata:
  labels:
    app: bff-impostos-tributos
  name: bff-impostos-tributos
  namespace: bikini
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: bff-impostos-tributos
