apiVersion: v1
kind: Service
metadata:
  labels:
    app: bff-interoperabilidade
  name: bff-interoperabilidade
  namespace: rio
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: bff-interoperabilidade
