apiVersion: v1
kind: Service
metadata:
  labels:
    app: bff-sqctrl-legado
  name: bff-sqctrl-legado
  namespace: staging1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: bff-sqctrl-legado
