apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-staging3-pv-config
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/staging3/config

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-staging3-pv-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/staging3/data

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-staging3-pv-exports
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/staging3/exports

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-staging3-pv-filesportal
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/staging3/filesportal

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-staging3-pv-imports
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/staging3/imports

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-staging3-pv-shared
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/staging3/shared

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-staging3-pv-upload
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/staging3/upload

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-certs-pv
  namespace: staging3
spec:
  capacity:
    storage: 1Gi  
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: premium-rwo
  hostPath:
    path: /opt/certs/ 
    #type: Directory 

