apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-ibiza-pv-config
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/ibiza/config

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-ibiza-pv-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/ibiza/data

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-ibiza-pv-exports
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/ibiza/exports

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-ibiza-pv-filesportal
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/ibiza/filesportal

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-ibiza-pv-imports
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/ibiza/imports

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-ibiza-pv-shared
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/ibiza/shared

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-ibiza-pv-upload
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/ibiza/upload

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-certs-pv
  namespace: ibiza
spec:
  capacity:
    storage: 1Gi  
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: premium-rwo
  hostPath:
    path: /opt/certs/ 
    #type: Directory 

