apiVersion: v1
kind: Service
metadata:
  labels:
    app: mfe-sqctrl-legado
  name: mfe-sqctrl-legado
  namespace: staging3
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: mfe-sqctrl-legado
