apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-pv-config
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/staging1/config

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-pv-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/staging1/data

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-pv-exports
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/staging1/exports

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-pv-filesportal
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/staging1/filesportal

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-pv-imports
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/staging1/imports

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-pv-shared
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/staging1/shared

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqctrl-pv-upload
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: premium-rwo
  hostPath:
    path: /sqctrl/staging1/upload
