apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-config-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard   # Tipo de disco, pode ser pd-standard ou pd-ssd
  fsType: ext4         # Sistema de arquivos
reclaimPolicy: Retain  # Política de retenção para o volume
volumeBindingMode: WaitForFirstConsumer  # O volume será provisionado quando o pod for agendado
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-data-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-exports-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-imports-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-shared-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd   # Usando SSD para volumes compartilhados
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-upload-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd   # Usando SSD para upload de arquivos
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-filesportal-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd   # Usando SSD para arquivos no portal
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
