apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-param-favoritos
  name: svc-param-favoritos
  namespace: staging1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: svc-param-favoritos
