apiVersion: v1
kind: Service
metadata:
  labels:
    app: bff-gestao-carteiras
  name: bff-gestao-carteiras
  namespace: miami
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: bff-gestao-carteiras
