apiVersion: v1
kind: Service
metadata:
  labels:
    app: bff-shell
  name: bff-shell
  namespace: staging2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: bff-shell
